name: Build and Test

on:
  push:
    branches: 
      - "main" 
      - "develop"
  pull_request:
    branches:
      - "main" 

jobs:
  build:
    name: Build and analyze GoalsApp scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Xcodegen
        run: brew install xcodegen

      - name: Install Swiftlint
        run: brew install swiftlint

      - name: Move to Application Directory
        run: cd Application

      - name: Run Xcodegen
        run: |
          cd Application
          xcodegen generate

      - name: Set Default Scheme
        run: |
          cd Application
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'].include?('GoalsApp') ? 'GoalsApp' : JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default

      - name: Build
        run: |
          cd Application
          xcodebuild clean build analyze -workspace Goals.xcworkspace -scheme GoalsApp -destination "platform=iOS Simulator,name=iPhone 15,OS=17.0.1" | xcpretty && exit ${PIPESTATUS[0]}

  test:
    name: Run Tests for GoalsApp
    runs-on: macos-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Xcodegen
        run: brew install xcodegen

      - name: Install Swiftlint
        run: brew install swiftlint

      - name: Move to Application Directory
        run: cd Application

      - name: Run Xcodegen
        run: |
          cd Application
          xcodegen generate

      - name: Run Tests
        run: |
          cd Application
          xcodebuild test -workspace Goals.xcworkspace -scheme GoalsTests -destination "platform=iOS Simulator,name=iPhone 15,OS=17.0.1" | xcpretty && exit ${PIPESTATUS[0]}

