name: Build and Test

on:
  push:
    branches: 
      - "develop"
  pull_request:
    branches:
      - "main" 

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          brew install xcodegen swiftlint lcov
          xcrun simctl create "iPhone 15" com.apple.CoreSimulator.SimDeviceType.iPhone-15 com.apple.CoreSimulator.SimRuntime.iOS-17-0
          
  build:
    needs: setup
    runs-on: macos-latest
    steps:
      - name: Build
        run: |
          cd Application
          xcodegen generate
          xcodebuild clean build analyze -workspace Goals.xcworkspace -scheme GoalsApp -destination "platform=iOS Simulator,name=iPhone 15,OS=17.0.1" | xcpretty && exit ${PIPESTATUS[0]}

  test:
    needs: build
    runs-on: macos-latest
    steps:
      - name: Run Tests with Coverage
        run: |
          cd Application
          xcodebuild test -workspace Goals.xcworkspace -scheme GoalsTests -destination "platform=iOS Simulator,name=iPhone 15,OS=17.0.1" -enableCodeCoverage YES -derivedDataPath DerivedData | xcpretty && exit ${PIPESTATUS[0]}
          
      - name: Generate LCOV Report
        run: |
          chmod +x ./Scripts/generate_lcov.sh
          ./Scripts/generate_lcov.sh
